# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update-changelog:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs: 
      changelog: changelog.md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Generate the change log
    - name: Generate changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.2
