name: Speccy JSON Validation CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: validate JSON URL scheme
      run: |
        docker run wework/speccy lint -v -j https://raw.githubusercontent.com/${{github.repository}}/${GITHUB_REF##*/}/url-schemes/exampleUrlScheme.json

